Travel/Travel/Models/Detail.cs
using Microsoft.EntityFrameworkCore;

//Creamos la propiedad de la vista como si fuera una entidad normal

namespace Travel.Models{
    //Esta propiedad indica que no maneja una llave primaria al ser una vista. 
    [Keyless]
    public class Detail{
       public string Nombre { get; set; } 
       public string Apellidos { get; set; }
       public string Titulo { get; set; }
       public string Sinopsis { get; set; }
       public string N_paginas { get; set; }
       public int Isbn { get; set; }
       public string Editorial { get; set; }
    }
}

Travel/Travel/Models/ErrorViewModel.cs
using System;

namespace Travel.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Travel/Travel/Controllers/BibliotecaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Travel.Data;
using Travel.Models;

namespace Travel.Controllers
{
    public class BibliotecaController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        //Creammos una instancia del data context para poder manejar la conexión a la base de datos
        public readonly applicationDataBaseContext _db;

        //Implementamos el datacontext en el controlador y le asignamos el valor
        public BibliotecaController(applicationDataBaseContext db, ILogger<HomeController> logger)
        {
            _db = db;
            _logger = logger;
        }

        //Traemos la propiedad a utilizar y le damos el valor del data context para recueperar la información
        public IActionResult Index()
        {
            IEnumerable<Detail> details = _db.Details;
            return View(details);
        }
    }
}

Travel/Travel/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Travel.Data;
using Travel.Models;

namespace Travel.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly applicationDataBaseContext _db;

        public HomeController(ILogger<HomeController> logger, applicationDataBaseContext db)
        {
            _logger = logger;
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Consulta()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Travel/Travel/Views/Biblioteca/Index.cshtml
@model IEnumerable<Travel.Models.Detail>

@{
    ViewData["Title"] = "Books";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Detalle de Libros</h2>
        </div>
    </div>
    <br />

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Nombre
                </th>
                <th>
                    Apellido
                </th>
                <th>
                    Libro
                </th>
                <th>
                    Sinopsis
                </th>
                <th>
                    # Paginas
                </th>
                <th>
                    ISBN
                </th>
                <th>
                    Editorial
                </th>
            </tr>
        </thead>
        <tbody>

            @foreach (var detalle in Model)
            {
                <tr>
                    <td width="30%">@detalle.Nombre</td>
                    <td width="30%">@detalle.Apellidos</td>
                    <td width="30%">@detalle.Titulo</td>
                    <td width="100%">@detalle.Sinopsis</td>
                    <td width="30%">@detalle.N_paginas</td>
                    <td width="30%">@detalle.Isbn</td>
                    <td width="30%">@detalle.Editorial</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Travel/Travel/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome To Travel</h1>
    <p>For the moment, we only can show you our inventory, please be patient while we working to be better for you</a>.</p>
</div>

Travel/Travel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Travel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Biblioteca" asp-action="Index">Inventario</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Travel Library
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>